Feature/update docker setup
openbase/bco.website pull request #38
Opened 2023-10-10 20:41 UTC by LukBelter

Updated Docker setup documentation.

2023-10-10 20:45 UTC, LukBelter reviewed
Added missing sudo & changed bco_net into bco-net

2023-10-10 20:45 UTC, LukBelter commented on www/user/howto/bco-demo.md
> +docker run \
```suggestion
sudo docker run \
```

2023-10-10 20:45 UTC, LukBelter commented on www/user/howto/setup-docker.md
> +docker run \
```suggestion
sudo docker run \
```

2023-10-10 20:45 UTC, LukBelter commented on www/user/howto/setup-docker.md
> +    --net=bco_net \
```suggestion
    --net=bco-net \
```

2023-10-10 20:45 UTC, LukBelter commented on www/user/howto/setup-docker.md
> +    --net=bco_net \
```suggestion
    --net=bco-net \
```

2023-10-31 19:48 UTC, DivineThreepwood requested changes
minor changes requested

2023-10-31 19:48 UTC, DivineThreepwood commented on www/user/howto/bco-demo.md
> +openbaseorg/bco-demo:beta
```suggestion
openbaseorg/bco-demo:stable
```

2023-10-31 19:48 UTC, DivineThreepwood commented on www/user/howto/bco-demo.md
> +--env BCO_OPTIONS='--db /tmp/bco/db --simulate --host mosquitto' \
```suggestion
--env BCO_OPTIONS='--db /tmp/bco/db --simulate --host mqtt-broker' \
```

2023-10-31 19:48 UTC, DivineThreepwood commented on www/user/howto/setup-docker.md
> +--name mosquitto \
```suggestion
--name mqtt-broker \
```

2023-10-31 21:04 UTC, DivineThreepwood commented on www/user/howto/setup-docker.md
> +docker network create bco-net
```suggestion
sudo docker network create bco-net
```

2023-11-01 01:18 UTC, DivineThreepwood approved these changes

2023-11-01 01:18 UTC, merged